// adminkit/resources/js/pages/Committees.vue
<script setup>
import { computed, ref } from 'vue';
import { Head, router, useForm, usePage } from '@inertiajs/vue3';
import { Gavel, Loader2, Pencil, Plus, Save, Scale, Trash2, X } from 'lucide-vue-next';

import AppLayout from '@/components/layout/AppLayout.vue';
import { menuLabelOf } from '@/composables/useMenuLabel';
import Badge from '@/components/ui/Badge.vue';
import Button from '@/components/ui/Button.vue';
import Combobox from '@/components/ui/Combobox.vue';
import Dialog from '@/components/ui/Dialog.vue';
import DropdownMenuItem from '@/components/ui/DropdownMenuItem.vue';
import DropdownMenuSeparator from '@/components/ui/DropdownMenuSeparator.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';
import Switch from '@/components/ui/Switch.vue';
import ConfirmDeleteDialog from '@/components/composite/ConfirmDeleteDialog.vue';
import DataTableCard from '@/components/composite/DataTableCard.vue';
import RowActions from '@/components/composite/RowActions.vue';
import { ACTION } from '@/constants/labels';
import { MECHANISM_OPTIONS } from '@/constants/committee';

const props = defineProps({
    paths: { type: Array, required: true },
    productOptions: { type: Array, default: () => [] },
    pathOptions: { type: Array, default: () => [] },
});

const page = usePage();
const canManage = computed(() =>
    (page.props.auth?.user?.permissions ?? []).includes('committees.manage'),
);
const pageTitle = computed(() => menuLabelOf('/committees', 'Komite Kredit'));

const columns = [
    { key: 'product_label', label: 'Produk' },
    { key: 'condition_label', label: 'Kondisi / Kategori' },
    { key: 'mechanism_label', label: 'Mekanisme' },
    { key: 'tiers_count', label: 'Jenjang', align: 'right' },
    { key: 'status_label', label: 'Status', sortable: false },
    { key: 'actions', label: '', align: 'right', width: '48px', sortable: false },
];

const dialogOpen = ref(false);
const editing = ref(null);
const form = useForm({
    product_id: '',
    condition: '',
    mechanism: 'plafon',
    is_active: true,
    note: '',
    copy_from: '',
});

const openCreate = () => {
    editing.value = null;
    form.clearErrors();
    form.defaults({ product_id: '', condition: '', mechanism: 'plafon', is_active: true, note: '', copy_from: '' });
    form.reset();
    dialogOpen.value = true;
};

const openEdit = (row) => {
    editing.value = row;
    form.clearErrors();
    form.defaults({
        product_id: row.product_id ? String(row.product_id) : '',
        condition: row.condition ?? '',
        mechanism: row.mechanism,
        is_active: row.is_active,
        note: row.note ?? '',
        copy_from: '',
    });
    form.reset();
    dialogOpen.value = true;
};

const submit = () => {
    const options = { preserveScroll: true, onSuccess: () => (dialogOpen.value = false) };

    if (editing.value) form.put(`/committees/${editing.value.id}`, options);
    else form.post('/committees', options);
};

const deleting = ref(null);
const rowForm = useForm({});
const confirmDelete = () =>
    rowForm.delete(`/committees/${deleting.value.id}`, {
        preserveScroll: true,
        onFinish: () => (deleting.value = null),
    });

const copyOptions = computed(() => [
    { value: '', label: 'Tidak menyalin' },
    ...props.pathOptions,
]);
</script>

<template>
    <Head :title="pageTitle" />
    <AppLayout>
        <div class="space-y-6" data-testid="committees-page-view">
            <DataTableCard
                :title="pageTitle"
                testid="committees"
                :columns="columns"
                :rows="props.paths"
                :empty-icon="Gavel"
                empty-title="Belum ada jalur komite"
                empty-description="Buat jalur per produk (atau lintas produk untuk kondisi seperti RELOAN), lalu susun jenjang kewenangannya."
                :show-refresh="false"
                row-clickable
                @row-click="router.visit(`/committees/${$event.id}`)"
            >
                <template #header-action>
                    <Button v-if="canManage" size="sm" data-testid="committees-add" @click="openCreate">
                        <Plus class="size-4" /> {{ ACTION.add }}
                    </Button>
                </template>

                <template #cell-product_label="{ row }">
                    <span class="font-medium">{{ row.product_label }}</span>
                </template>

                <template #cell-condition_label="{ row }">
                    <Badge :variant="row.condition ? 'default' : 'secondary'" class="font-medium">
                        {{ row.condition_label }}
                    </Badge>
                </template>

                <template #cell-mechanism_label="{ row }">
                    <span class="inline-flex items-center gap-1.5">
                        <Scale class="size-3.5 text-muted-foreground" />{{ row.mechanism_label }}
                    </span>
                </template>

                <template #cell-status_label="{ row }">
                    <Badge :variant="row.is_active ? 'secondary' : 'destructive'" class="font-medium">
                        {{ row.status_label }}
                    </Badge>
                </template>

                <template #cell-actions="{ row }">
                    <RowActions v-if="canManage" :testid="`committees-actions-${row.id}`">
                        <DropdownMenuItem
                            :data-testid="`committees-detail-${row.id}`"
                            @select="router.visit(`/committees/${row.id}`)"
                        >
                            <Gavel />Kelola Jenjang
                        </DropdownMenuItem>
                        <DropdownMenuItem :data-testid="`committees-edit-${row.id}`" @select="openEdit(row)">
                            <Pencil />{{ ACTION.edit }}
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                            class="text-destructive data-[highlighted]:text-destructive"
                            :data-testid="`committees-delete-${row.id}`"
                            @click="deleting = row"
                        >
                            <Trash2 />{{ ACTION.delete }}
                        </DropdownMenuItem>
                    </RowActions>
                </template>
            </DataTableCard>

            <Dialog
                v-model:open="dialogOpen"
                :title="`${editing ? ACTION.edit : ACTION.add} Jalur Komite`"
                class="max-w-md"
            >
                <form id="path-form" class="form-dense space-y-[var(--field-gap)]" novalidate @submit.prevent="submit">
                    <div class="space-y-[var(--item-gap)]">
                        <Label>Produk</Label>
                        <Combobox
                            v-model="form.product_id"
                            :options="props.productOptions"
                            placeholder="Semua Produk"
                            data-testid="committees-form-product"
                        />
                        <p v-if="form.errors.product_id" class="text-xs font-medium text-destructive">
                            {{ form.errors.product_id }}
                        </p>
                    </div>
                    <div class="space-y-[var(--item-gap)]">
                        <Label for="path-condition">Kondisi / Kategori</Label>
                        <Input
                            id="path-condition"
                            v-model="form.condition"
                            class="uppercase"
                            placeholder="Kosongkan untuk Normal"
                            maxlength="30"
                            autocomplete="off"
                            data-testid="committees-form-condition"
                        />
                        <p v-if="form.errors.condition" class="text-xs font-medium text-destructive" data-testid="committees-form-condition-error">
                            {{ form.errors.condition }}
                        </p>
                    </div>
                    <div class="space-y-[var(--item-gap)]">
                        <Label>Mekanisme</Label>
                        <Combobox
                            v-model="form.mechanism"
                            :options="MECHANISM_OPTIONS"
                            data-testid="committees-form-mechanism"
                        />
                        <p v-if="form.errors.mechanism" class="text-xs font-medium text-destructive">
                            {{ form.errors.mechanism }}
                        </p>
                    </div>
                    <div v-if="!editing" class="space-y-[var(--item-gap)]">
                        <Label>Salin Jenjang Dari</Label>
                        <Combobox
                            v-model="form.copy_from"
                            :options="copyOptions"
                            placeholder="Tidak menyalin"
                            data-testid="committees-form-copy"
                        />
                    </div>
                    <div class="space-y-[var(--item-gap)]">
                        <Label for="path-note">Catatan</Label>
                        <Input
                            id="path-note"
                            v-model="form.note"
                            maxlength="255"
                            autocomplete="off"
                            data-testid="committees-form-note"
                        />
                    </div>
                    <label class="flex items-center justify-between gap-3 pt-1">
                        <span class="text-sm">Aktif</span>
                        <Switch v-model="form.is_active" data-testid="committees-form-active" />
                    </label>
                </form>

                <template #footer>
                    <Button variant="outline" size="sm" data-testid="committees-form-cancel" @click="dialogOpen = false">
                        <X class="size-4" /> {{ ACTION.cancel }}
                    </Button>
                    <Button
                        size="sm"
                        type="submit"
                        form="path-form"
                        :disabled="form.processing"
                        data-testid="committees-form-save"
                    >
                        <Loader2 v-if="form.processing" class="size-4 animate-spin" />
                        <Save v-else class="size-4" />
                        {{ form.processing ? ACTION.saving : ACTION.save }}
                    </Button>
                </template>
            </Dialog>

            <ConfirmDeleteDialog
                :open="Boolean(deleting)"
                title="Hapus Jalur Komite?"
                description="Seluruh jenjang pada jalur ini ikut terhapus dan tidak dapat dipulihkan."
                :processing="rowForm.processing"
                @update:open="deleting = null"
                @confirm="confirmDelete"
            />
        </div>
    </AppLayout>
</template>

// resources/js/pages/committees/index.tsx
import { Head, router, useForm } from '@inertiajs/react';
import {
    Gavel,
    MoreHorizontal,
    Pencil,
    Plus,
    Scale,
    Trash2,
} from 'lucide-react';
import { useState } from 'react';
import { AuthorityCheck } from '@/pages/committees/authority-check';
import { Button } from '@/components/ui/button';
import { Combobox } from '@/components/ui/combobox';
import { ConfirmDialog, DialogFooter, Modal } from '@/components/ui/dialog';
import {
    DropdownContent,
    DropdownItem,
    DropdownMenu,
    DropdownSeparator,
    DropdownTrigger,
} from '@/components/ui/dropdown';
import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { DataTable } from '@/components/ui/data-table';
import type { Column } from '@/components/ui/data-table';
import { Badge, PageHeader } from '@/components/ui/misc';
import { Tip } from '@/components/ui/tooltip';

type Option = { value: number | string; label: string };
export type PathRow = {
    id: number;
    product_id: number | null;
    product_label: string;
    condition: string | null;
    condition_label: string;
    mechanism: string;
    mechanism_label: string;
    is_active: boolean;
    note: string | null;
    tiers_count: number;
    title: string;
};

type Props = {
    paths: PathRow[];
    productOptions: Option[];
    pathOptions: Option[];
    conditionMap: Record<string, string[]>;
    mechanisms: Option[];
    canManage: boolean;
};

export default function CommitteesIndex({
    paths,
    productOptions,
    pathOptions,
    conditionMap,
    mechanisms,
    canManage,
}: Props) {
    const [editing, setEditing] = useState<PathRow | 'new' | null>(null);
    const [toDelete, setToDelete] = useState<PathRow | null>(null);
    const [checking, setChecking] = useState(false);
    const [deleting, setDeleting] = useState(false);
    const form = useForm({
        product_id: '',
        condition: '',
        mechanism: 'plafon',
        is_active: true,
        note: '',
        copy_from: '',
    });

    const openForm = (row: PathRow | 'new') => {
        form.clearErrors();
        form.setData(
            row === 'new'
                ? {
                      product_id: '',
                      condition: '',
                      mechanism: 'plafon',
                      is_active: true,
                      note: '',
                      copy_from: '',
                  }
                : {
                      product_id: row.product_id ? String(row.product_id) : '',
                      condition: row.condition ?? '',
                      mechanism: row.mechanism,
                      is_active: row.is_active,
                      note: row.note ?? '',
                      copy_from: '',
                  },
        );
        setEditing(row);
    };

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        const options = {
            preserveScroll: true,
            onSuccess: () => setEditing(null),
        };
        if (editing === 'new') {
            form.post('/committees', options);
        } else if (editing) {
            form.put(`/committees/${editing.id}`, options);
        }
    };

    const confirmDelete = () => {
        if (!toDelete) {
            return;
        }
        router.delete(`/committees/${toDelete.id}`, {
            onStart: () => setDeleting(true),
            onFinish: () => {
                setDeleting(false);
                setToDelete(null);
            },
        });
    };

    const columns: Column<PathRow>[] = [
        {
            key: 'product',
            header: 'Product',
            className: 'font-medium',
            cell: (p) => p.product_label,
        },
        {
            key: 'condition',
            header: 'Condition',
            hideBelow: 'sm',
            cell: (p) => p.condition_label,
        },
        {
            key: 'mechanism',
            header: 'Mechanism',
            hideBelow: 'md',
            cell: (p) => p.mechanism_label,
        },
        {
            key: 'tiers',
            header: 'Tiers',
            align: 'right',
            hideBelow: 'sm',
            className: 'tabular-nums',
            cell: (p) => p.tiers_count,
        },
        {
            key: 'status',
            header: 'Status',
            cell: (p) => (
                <Badge tone={p.is_active ? 'success' : 'neutral'}>
                    {p.is_active ? 'Active' : 'Inactive'}
                </Badge>
            ),
        },
        {
            key: 'actions',
            header: 'Actions',
            srOnly: true,
            narrow: true,
            align: 'right',
            cell: (p) =>
                canManage && (
                    <DropdownMenu>
                        <Tip label="Actions">
                            <DropdownTrigger asChild>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    aria-label={`Actions for ${p.title}`}
                                >
                                    <MoreHorizontal />
                                </Button>
                            </DropdownTrigger>
                        </Tip>
                        <DropdownContent>
                            <DropdownItem
                                icon={<Pencil />}
                                onSelect={() => openForm(p)}
                            >
                                Edit
                            </DropdownItem>
                            <DropdownSeparator />
                            <DropdownItem
                                danger
                                icon={<Trash2 />}
                                onSelect={() => setToDelete(p)}
                            >
                                Delete
                            </DropdownItem>
                        </DropdownContent>
                    </DropdownMenu>
                ),
        },
    ];

    return (
        <>
            <Head title="Committees" />
            <PageHeader
                title="Committees"
                description="Who may decide a loan, by product, condition and amount"
                actions={
                    <>
                        <Button
                            variant="outline"
                            onClick={() => setChecking(true)}
                        >
                            <Scale /> Check authority
                        </Button>
                        {canManage && (
                            <Button onClick={() => openForm('new')}>
                                <Plus /> Add path
                            </Button>
                        )}
                    </>
                }
            />

            <DataTable
                rows={paths}
                rowKey={(p) => p.id}
                columns={columns}
                onRowClick={(p) => router.visit(`/committees/${p.id}`)}
                empty={{
                    icon: <Gavel />,
                    title: 'No committee paths yet',
                    description:
                        'Create a path per product (or across products for conditions such as RELOAN), then define its tiers.',
                    action: canManage ? (
                        <Button size="sm" onClick={() => openForm('new')}>
                            <Plus /> Add path
                        </Button>
                    ) : undefined,
                }}
            />

            <Modal
                open={editing !== null}
                onOpenChange={(open) => !open && setEditing(null)}
                title={
                    editing === 'new'
                        ? 'Add committee path'
                        : 'Edit committee path'
                }
                description="One path per product and condition."
            >
                <form onSubmit={submit} noValidate>
                    <div className="flex flex-col gap-3 p-4">
                        <Field
                            label="Product"
                            error={form.errors.product_id}
                            hint="Leave empty to apply to all products."
                        >
                            <Combobox
                                clearable
                                placeholder="All products"
                                options={productOptions}
                                value={form.data.product_id}
                                onChange={(v) =>
                                    form.setData('product_id', v ?? '')
                                }
                                invalid={!!form.errors.product_id}
                            />
                        </Field>
                        <Field
                            label="Condition / category"
                            error={form.errors.condition}
                            hint="Empty means Normal. Stored in uppercase, e.g. RELOAN."
                        >
                            <Input
                                className="uppercase"
                                value={form.data.condition}
                                maxLength={30}
                                onChange={(e) =>
                                    form.setData('condition', e.target.value)
                                }
                                aria-invalid={!!form.errors.condition}
                            />
                        </Field>
                        <Field
                            label="Mechanism"
                            required
                            error={form.errors.mechanism}
                        >
                            <Combobox
                                searchable={false}
                                options={mechanisms}
                                value={form.data.mechanism}
                                onChange={(v) =>
                                    form.setData('mechanism', v ?? 'plafon')
                                }
                                invalid={!!form.errors.mechanism}
                            />
                        </Field>
                        {editing === 'new' && (
                            <Field
                                label="Copy tiers from"
                                error={form.errors.copy_from}
                            >
                                <Combobox
                                    clearable
                                    placeholder="Do not copy"
                                    options={pathOptions}
                                    value={form.data.copy_from}
                                    onChange={(v) =>
                                        form.setData('copy_from', v ?? '')
                                    }
                                />
                            </Field>
                        )}
                        <Field label="Note" error={form.errors.note}>
                            <Input
                                value={form.data.note}
                                maxLength={255}
                                onChange={(e) =>
                                    form.setData('note', e.target.value)
                                }
                            />
                        </Field>
                        <label className="flex items-center gap-2 text-sm">
                            <input
                                type="checkbox"
                                className="accent-primary"
                                checked={form.data.is_active}
                                onChange={(e) =>
                                    form.setData('is_active', e.target.checked)
                                }
                            />
                            Active
                        </label>
                    </div>
                    <DialogFooter>
                        <Button
                            variant="outline"
                            onClick={() => setEditing(null)}
                        >
                            Cancel
                        </Button>
                        <Button type="submit" loading={form.processing}>
                            {editing === 'new' ? 'Create' : 'Save'}
                        </Button>
                    </DialogFooter>
                </form>
            </Modal>

            <ConfirmDialog
                open={toDelete !== null}
                onOpenChange={(open) => !open && !deleting && setToDelete(null)}
                title="Delete committee path?"
                description={
                    <>
                        This removes <strong>{toDelete?.title}</strong> and all
                        of its tiers.
                    </>
                }
                loading={deleting}
                onConfirm={confirmDelete}
            />

            <AuthorityCheck
                open={checking}
                onOpenChange={setChecking}
                productOptions={productOptions}
                conditionMap={conditionMap}
            />
        </>
    );
}
