// adminkit/resources/js/pages/Scheduling.vue
<script setup>
import { computed, ref } from 'vue';
import { CalendarCheck, CalendarClock, History, Loader2 } from 'lucide-vue-next';
import { Head, useForm } from '@inertiajs/vue3';

import AppLayout from '@/components/layout/AppLayout.vue';
import Badge from '@/components/ui/Badge.vue';
import Button from '@/components/ui/Button.vue';
import Combobox from '@/components/ui/Combobox.vue';
import Dialog from '@/components/ui/Dialog.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';
import DataTableCard from '@/components/composite/DataTableCard.vue';
import { ACTION } from '@/constants/labels';
import { rupiah } from '@/constants/committee';
import { useServerTable } from '@/composables/useServerTable';

const props = defineProps({
    records: { type: Object, required: true },
    filters: { type: Object, default: () => ({}) },
    statuses: { type: Array, default: () => [] },
    surveyorOptions: { type: Array, default: () => [] },
    maxSchedules: { type: Number, default: 3 },
});

const columns = [
    { key: 'application_code', label: 'Kode Pengajuan' },
    { key: 'full_name', label: 'Pemohon' },
    { key: 'product_label', label: 'Produk', hideBelow: 'lg', sortable: false },
    { key: 'survey_date', label: 'Jadwal Survei', hideBelow: 'md' },
    { key: 'status', label: 'Status', hideBelow: 'sm' },
    { key: 'actions', label: '', align: 'right', width: '140px', sortable: false },
];

const { query, loading, reload, onSearch, onSort, onPage, onPerPage, onFilter, sortState } = useServerTable({
    url: '/scheduling-simulation',
    only: ['records', 'filters'],
    initial: {
        search: props.filters.search ?? '',
        sort: props.filters.sort ?? 'application_date',
        dir: props.filters.dir ?? 'asc',
        status: props.filters.status ?? '',
        scope: props.filters.scope ?? 'saya',
        page: props.records.meta.page ?? 1,
        per_page: props.records.meta.per_page ?? 10,
    },
});

const statusOptions = computed(() => [
    { value: '', label: 'Semua status' },
    ...props.statuses.map((s) => ({ value: s, label: s })),
]);

const scopeOptions = [
    { value: 'saya', label: 'Berkas saya' },
    { value: 'semua', label: 'Semua Kasi Analis' },
];

const today = new Date().toISOString().slice(0, 10);

const scheduling = ref(null);
const form = useForm({ survey_date: '', surveyor_id: '', note: '' });

const openSchedule = (row) => {
    form.defaults({
        survey_date: row.survey_date ?? today,
        surveyor_id: row.surveyor_id ?? '',
        note: '',
    });
    form.reset();
    form.clearErrors();
    scheduling.value = row;
};

const submit = () =>
    form.post(`/scheduling-simulation/${scheduling.value.id}`, {
        preserveScroll: true,
        onSuccess: () => (scheduling.value = null),
    });

const history = ref(null);

const ACTION_TONE = {
    JADWAL: 'secondary',
    'JADWAL ULANG': 'default',
    BATAL: 'destructive',
};
</script>

<template>
    <Head title="Penjadwalan Survei" />
    <AppLayout>
        <div class="space-y-4" data-testid="scheduling-page">
            <DataTableCard
                server
                title="Penjadwalan Survei"
                testid="scheduling"
                :columns="columns"
                :rows="props.records.data"
                :meta="props.records.meta"
                :search="query.search"
                :sort="sortState"
                :loading="loading"
                :empty-icon="CalendarClock"
                empty-title="Belum ada berkas untuk dijadwalkan"
                empty-description="Berkas muncul di sini setelah petugas menekan Ajukan pada Pengajuan Kredit."
                @update:search="onSearch"
                @update:sort="onSort"
                @update:page="onPage"
                @update:per-page="onPerPage"
                @refresh="reload()"
            >
                <template #filters>
                    <Combobox
                        :model-value="query.scope"
                        :options="scopeOptions"
                        placeholder="Berkas saya"
                        class="w-full sm:w-[190px]"
                        data-testid="scheduling-scope-filter"
                        @update:model-value="onFilter('scope', $event)"
                    />
                    <Combobox
                        :model-value="query.status"
                        :options="statusOptions"
                        placeholder="Semua status"
                        class="w-full sm:w-[180px]"
                        data-testid="scheduling-status-filter"
                        @update:model-value="onFilter('status', $event)"
                    />
                </template>

                <template #cell-application_code="{ row }">
                    <span class="block whitespace-nowrap font-mono text-xs font-medium">{{ row.application_code }}</span>
                    <span class="mt-0.5 block whitespace-nowrap text-xs text-muted-foreground">
                        {{ row.application_date }}
                    </span>
                </template>

                <template #cell-full_name="{ row }">
                    <span class="block font-medium">{{ row.full_name }}</span>
                    <span class="block whitespace-nowrap text-xs text-muted-foreground">
                        {{ rupiah(row.requested_amount) }} · {{ row.requested_tenor ? `${row.requested_tenor} bln` : '—' }}
                    </span>
                </template>

                <template #cell-product_label="{ row }">
                    <span class="block whitespace-normal">{{ row.product_label ?? '—' }}</span>
                    <span class="mt-0.5 block whitespace-normal text-xs text-muted-foreground">
                        Kasi: {{ row.supervisor_name ?? '—' }}
                    </span>
                </template>

                <template #cell-survey_date="{ row }">
                    <span class="block whitespace-nowrap">{{ row.survey_date_label ?? '—' }}</span>
                    <span class="mt-0.5 block whitespace-normal text-xs text-muted-foreground">
                        {{ row.surveyor_name ?? 'Belum ditugaskan' }}
                    </span>
                </template>

                <template #cell-status="{ row }">
                    <Badge :variant="row.status === 'PENJADWALAN' ? 'default' : 'secondary'" class="font-medium">
                        {{ row.status }}
                    </Badge>
                    <span
                        class="mt-0.5 block whitespace-nowrap text-xs"
                        :class="row.over_limit ? 'font-medium text-destructive' : 'text-muted-foreground'"
                        :data-testid="`scheduling-count-${row.id}`"
                    >
                        Jadwal {{ row.schedule_count }}/{{ props.maxSchedules }}
                        <template v-if="row.over_limit">· lewat batas</template>
                    </span>
                </template>

                <template #cell-actions="{ row }">
                    <div class="flex items-center justify-end gap-1">
                        <Button
                            variant="ghost"
                            size="icon"
                            title="Histori penjadwalan"
                            :data-testid="`scheduling-history-${row.id}`"
                            @click="history = row"
                        >
                            <History class="size-4" />
                        </Button>
                        <Button
                            size="sm"
                            :data-testid="`scheduling-set-${row.id}`"
                            @click="openSchedule(row)"
                        >
                            <CalendarCheck class="size-4" />
                            {{ row.status === 'PENJADWALAN' ? 'Jadwal Ulang' : 'Jadwalkan' }}
                        </Button>
                    </div>
                </template>
            </DataTableCard>

            <Dialog
                :open="Boolean(scheduling)"
                :title="`Jadwal Survei ${scheduling?.application_code ?? ''}`"
                @update:open="scheduling = null"
            >
                <form class="form-dense space-y-3" @submit.prevent="submit">
                    <div class="space-y-[var(--item-gap)]">
                        <Label for="s-date">Tanggal Survei <span class="text-destructive">*</span></Label>
                        <Input
                            id="s-date"
                            v-model="form.survey_date"
                            type="date"
                            :min="today"
                            data-testid="scheduling-date"
                        />
                        <p v-if="form.errors.survey_date" class="text-xs font-medium text-destructive">
                            {{ form.errors.survey_date }}
                        </p>
                    </div>

                    <div class="space-y-[var(--item-gap)]">
                        <Label>Staff Analis <span class="text-destructive">*</span></Label>
                        <Combobox
                            v-model="form.surveyor_id"
                            :options="props.surveyorOptions"
                            placeholder="Pilih staff analis"
                            data-testid="scheduling-surveyor"
                        />
                        <p v-if="form.errors.surveyor_id" class="text-xs font-medium text-destructive">
                            {{ form.errors.surveyor_id }}
                        </p>
                    </div>

                    <div class="space-y-[var(--item-gap)]">
                        <Label for="s-note">Catatan</Label>
                        <Input
                            id="s-note"
                            v-model="form.note"
                            maxlength="255"
                            placeholder="Opsional"
                            data-testid="scheduling-note"
                        />
                        <p v-if="form.errors.note" class="text-xs font-medium text-destructive">
                            {{ form.errors.note }}
                        </p>
                    </div>

                    <p
                        v-if="scheduling?.over_limit"
                        class="rounded-md border border-destructive/40 bg-destructive/10 p-2 text-xs font-medium text-destructive"
                        data-testid="scheduling-over-limit-warning"
                    >
                        Berkas ini sudah dijadwalkan {{ scheduling.schedule_count }} kali (batas wajar
                        {{ props.maxSchedules }} kali). Penjadwalan masih boleh dilanjutkan, mohon ditinjau.
                    </p>
                    <p v-else class="text-xs text-muted-foreground">
                        Penjadwalan tercatat sebagai histori. Batas wajar {{ props.maxSchedules }} kali per berkas.
                    </p>
                </form>

                <template #footer>
                    <Button variant="outline" size="sm" data-testid="scheduling-cancel" @click="scheduling = null">
                        {{ ACTION.cancel }}
                    </Button>
                    <Button size="sm" :disabled="form.processing" data-testid="scheduling-submit" @click="submit">
                        <Loader2 v-if="form.processing" class="size-4 animate-spin" />
                        <CalendarCheck v-else class="size-4" />
                        {{ ACTION.save }}
                    </Button>
                </template>
            </Dialog>

            <Dialog
                :open="Boolean(history)"
                :title="`Histori Penjadwalan ${history?.application_code ?? ''}`"
                @update:open="history = null"
            >
                <div v-if="history?.history?.length" class="space-y-2" data-testid="scheduling-history-list">
                    <div
                        v-for="item in history.history"
                        :key="item.id"
                        class="rounded-md border p-2.5"
                    >
                        <div class="flex items-center justify-between gap-2">
                            <Badge :variant="ACTION_TONE[item.action] ?? 'secondary'" class="font-medium">
                                {{ item.action }} #{{ item.sequence }}
                            </Badge>
                            <span class="text-xs text-muted-foreground">{{ item.created_at }}</span>
                        </div>
                        <p class="mt-1.5 text-sm">
                            {{ item.survey_date ?? '—' }} · {{ item.surveyor_name ?? '—' }}
                        </p>
                        <p v-if="item.reason" class="text-xs text-destructive">Alasan: {{ item.reason }}</p>
                        <p v-else-if="item.note" class="text-xs text-muted-foreground">Catatan: {{ item.note }}</p>
                        <p class="mt-1 text-xs text-muted-foreground">Oleh {{ item.created_by }}</p>
                    </div>
                </div>
                <p v-else class="py-6 text-center text-sm text-muted-foreground">
                    Belum ada histori penjadwalan.
                </p>

                <template #footer>
                    <Button variant="outline" size="sm" data-testid="scheduling-history-close" @click="history = null">
                        {{ ACTION.close }}
                    </Button>
                </template>
            </Dialog>
        </div>
    </AppLayout>
</template>

// resources/js/pages/scheduling/index.tsx
import { Head, useForm } from '@inertiajs/react';
import {
    AlertTriangle,
    CalendarDays,
    CalendarPlus,
    History,
    MoreHorizontal,
    Ban,
    XCircle,
    X,
} from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { FilterBar, SearchInput } from '@/components/ui/filter-bar';
import { ReasonDialog } from '@/components/reason-dialog';
import { Combobox } from '@/components/ui/combobox';
import { DatePicker } from '@/components/ui/date-picker';
import { DialogFooter, Modal } from '@/components/ui/dialog';
import {
    DropdownContent,
    DropdownItem,
    DropdownMenu,
    DropdownSeparator,
    DropdownTrigger,
} from '@/components/ui/dropdown';
import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { DataTable } from '@/components/ui/data-table';
import type { Column } from '@/components/ui/data-table';
import { Badge, PageHeader } from '@/components/ui/misc';
import type { BadgeTone } from '@/components/ui/misc';
import type { PageMeta } from '@/components/ui/pagination';
import { nextSort } from '@/components/ui/sort-head';
import { Tip } from '@/components/ui/tooltip';
import { useListQuery } from '@/hooks/use-list-query';
import { formatDate, rupiah } from '@/lib/format';

type Option = { value: string | number; label: string };
type Row = {
    id: number;
    application_code: string;
    application_date: string;
    full_name: string;
    nik: string;
    status: string;
    status_label: string;
    status_tone: BadgeTone;
    product_label: string | null;
    office_label: string | null;
    supervisor_name: string | null;
    surveyor_name: string | null;
    survey_date: string | null;
    requested_amount: number;
    requested_tenor: number;
    schedule_count: number;
    over_limit: boolean;
    walk_in: boolean;
    resurvey: boolean;
    needs_reschedule: boolean;
    sent_back_reason: string | null;
    surveyor_role: string;
    surveyor_options: Option[];
    can_cancel: boolean;
    history: {
        id: number;
        action: string;
        survey_date: string | null;
        surveyor_name: string | null;
        note: string | null;
        reason: string | null;
        created_by: string;
        created_at: string;
    }[];
};
type Filters = {
    search: string;
    status: string | null;
    scope: 'mine' | 'all';
    sort: string;
    direction: 'asc' | 'desc';
    per_page: number;
};

type Props = {
    loans: { data: Row[] } & PageMeta;
    filters: Filters;
    perPageOptions: number[];
    statuses: Option[];
    maxSchedules: number;
    canManage: boolean;
    canCancel: boolean;
};

const DEFAULTS = {
    status: 'submitted',
    sort: 'application_date',
    direction: 'desc',
    per_page: 10,
    scope: 'mine',
};

function ScheduleDialog({
    row,
    onClose,
}: {
    row: Row | null;
    onClose: () => void;
}) {
    const form = useForm({ survey_date: '', surveyor_id: '', note: '' });

    return (
        <Modal
            open={row !== null}
            onOpenChange={(open) => !open && onClose()}
            title={
                row?.resurvey
                    ? 'Jadwalkan survei ulang'
                    : row?.schedule_count
                      ? 'Jadwalkan ulang survei'
                      : 'Jadwalkan survei'
            }
            description={
                row ? `${row.application_code} · ${row.full_name}` : undefined
            }
        >
            {row && (
                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        form.post(`/scheduling/${row.id}`, {
                            preserveScroll: true,
                            onSuccess: () => {
                                form.reset();
                                onClose();
                            },
                        });
                    }}
                    noValidate
                >
                    <div className="flex flex-col gap-3 p-4">
                        {row.over_limit && (
                            <p className="flex items-start gap-1.5 rounded-md bg-amber-50 p-2 text-xs text-amber-700">
                                <AlertTriangle className="mt-0.5 size-3.5 shrink-0" />{' '}
                                Berkas ini sudah dijadwalkan{' '}
                                {row.schedule_count} kali. Pastikan masih layak
                                dilanjutkan.
                            </p>
                        )}
                        {row.walk_in && (
                            <p className="rounded-md bg-primary-soft p-2 text-xs text-primary">
                                Produk ini tanpa survei lapangan; berkas
                                langsung ke analisa.
                            </p>
                        )}
                        <Field
                            label="Tanggal survei"
                            required
                            error={form.errors.survey_date}
                        >
                            <DatePicker
                                id="survey_date"
                                min={new Date()}
                                max={
                                    new Date(
                                        new Date().getFullYear() + 1,
                                        11,
                                        31,
                                    )
                                }
                                value={form.data.survey_date}
                                onChange={(v) => form.setData('survey_date', v)}
                                invalid={!!form.errors.survey_date}
                            />
                        </Field>
                        <Field
                            label="Surveyor"
                            required
                            error={form.errors.surveyor_id}
                            hint={`Peran: ${row.surveyor_role}`}
                        >
                            <Combobox
                                options={row.surveyor_options}
                                placeholder={
                                    row.surveyor_options.length
                                        ? 'Pilih…'
                                        : 'Tidak ada pengguna dengan peran ini'
                                }
                                value={form.data.surveyor_id}
                                onChange={(v) =>
                                    form.setData('surveyor_id', v ?? '')
                                }
                                invalid={!!form.errors.surveyor_id}
                            />
                        </Field>
                        <Field label="Catatan" error={form.errors.note}>
                            <Input
                                value={form.data.note}
                                maxLength={255}
                                onChange={(e) =>
                                    form.setData('note', e.target.value)
                                }
                            />
                        </Field>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={onClose}>
                            Batal
                        </Button>
                        <Button type="submit" loading={form.processing}>
                            Simpan jadwal
                        </Button>
                    </DialogFooter>
                </form>
            )}
        </Modal>
    );
}

export default function SchedulingIndex({
    loans,
    filters,
    perPageOptions,
    statuses,
    canManage,
}: Props) {
    const [scheduling, setScheduling] = useState<Row | null>(null);
    const [history, setHistory] = useState<Row | null>(null);
    const [cancelUrl, setCancelUrl] = useState<string | null>(null);
    const [voidUrl, setVoidUrl] = useState<string | null>(null);
    const { visit, search, onSearch, clear, loading, error } =
        useListQuery<Filters>({
            url: '/scheduling',
            filters,
            defaults: DEFAULTS,
            only: ['loans', 'filters'],
        });
    const hasFilters = Boolean(
        filters.search || filters.status !== DEFAULTS.status,
    );
    const sortBy = (column: string) => visit(nextSort(filters, column));

    const columns: Column<Row>[] = [
        {
            key: 'file',
            header: 'Berkas',
            sort: 'application_code',
            cell: (l) => (
                <>
                    <p className="font-medium">{l.application_code}</p>
                    <p className="text-xs text-muted">{l.product_label}</p>
                </>
            ),
        },
        {
            key: 'applicant',
            header: 'Pemohon',
            sort: 'full_name',
            cell: (l) => (
                <>
                    {l.full_name}
                    <p className="text-xs text-muted">
                        {l.office_label ?? '–'} · {l.supervisor_name ?? '–'}
                    </p>
                </>
            ),
        },
        {
            key: 'amount',
            header: 'Plafon',
            align: 'right',
            hideBelow: 'md',
            className: 'whitespace-nowrap tabular-nums',
            cell: (l) => (
                <>
                    {rupiah(l.requested_amount)}
                    <p className="text-xs text-muted">
                        {l.requested_tenor} months
                    </p>
                </>
            ),
        },
        {
            key: 'survey',
            header: 'Survei',
            sort: 'survey_date',
            cell: (l) => (
                <>
                    {l.survey_date ? (
                        formatDate(l.survey_date)
                    ) : (
                        <span className="text-muted">Belum dijadwalkan</span>
                    )}
                    <p className="text-xs text-muted">
                        {l.surveyor_name ?? '–'}
                        {l.schedule_count > 0 && ` · ${l.schedule_count}×`}
                    </p>
                </>
            ),
        },
        {
            key: 'status',
            header: 'Status',
            sort: 'status',
            cell: (l) => (
                <span className="flex flex-wrap items-center gap-1">
                    {l.needs_reschedule ? (
                        <Tip
                            label={`Dikembalikan surveyor: ${l.sent_back_reason ?? ''}`}
                        >
                            <span>
                                <Badge tone="warning">
                                    Perlu dijadwalkan ulang
                                </Badge>
                            </span>
                        </Tip>
                    ) : (
                        <Badge tone={l.status_tone}>
                            {l.resurvey ? 'Disurvei' : l.status_label}
                        </Badge>
                    )}
                    {l.over_limit && (
                        <Tip label={`Dijadwalkan ${l.schedule_count} kali`}>
                            <span>
                                <AlertTriangle className="size-3.5 text-amber-600" />
                            </span>
                        </Tip>
                    )}
                </span>
            ),
        },
        {
            key: 'actions',
            header: 'Aksi',
            srOnly: true,
            narrow: true,
            align: 'right',
            cell: (l) => (
                <DropdownMenu>
                    <Tip label="Aksi">
                        <DropdownTrigger asChild>
                            <Button
                                variant="ghost"
                                size="icon"
                                aria-label={`Aksi untuk ${l.application_code}`}
                            >
                                <MoreHorizontal />
                            </Button>
                        </DropdownTrigger>
                    </Tip>
                    <DropdownContent>
                        {canManage && l.status !== 'scheduling' && (
                            <DropdownItem
                                icon={<CalendarPlus />}
                                onSelect={() => setScheduling(l)}
                            >
                                {l.resurvey
                                    ? 'Jadwalkan survei ulang'
                                    : l.schedule_count
                                      ? 'Jadwalkan ulang'
                                      : 'Jadwalkan survei'}
                            </DropdownItem>
                        )}
                        {canManage && l.status === 'scheduling' && (
                            <DropdownItem
                                icon={<CalendarPlus />}
                                onSelect={() => setScheduling(l)}
                            >
                                Jadwalkan ulang
                            </DropdownItem>
                        )}
                        {l.can_cancel && (
                            <DropdownItem
                                icon={<XCircle />}
                                onSelect={() =>
                                    setCancelUrl(`/scheduling/${l.id}/cancel`)
                                }
                            >
                                Batalkan jadwal
                            </DropdownItem>
                        )}
                        <DropdownItem
                            icon={<History />}
                            onSelect={() => setHistory(l)}
                        >
                            Riwayat
                        </DropdownItem>
                        {canManage && (
                            <>
                                <DropdownSeparator />
                                <DropdownItem
                                    danger
                                    icon={<Ban />}
                                    onSelect={() =>
                                        setVoidUrl(`/scheduling/${l.id}/void`)
                                    }
                                >
                                    Batalkan pengajuan
                                </DropdownItem>
                            </>
                        )}
                    </DropdownContent>
                </DropdownMenu>
            ),
        },
    ];

    return (
        <>
            <Head title="Penjadwalan" />
            <PageHeader
                title="Penjadwalan"
                description="Tentukan tanggal survei dan surveyor untuk berkas yang diajukan"
            />

            <DataTable
                rows={loans.data}
                rowKey={(r) => r.id}
                loading={loading}
                error={error}
                onRetry={() => visit({})}
                toolbar={
                    <FilterBar
                        search={
                            <SearchInput
                                value={search}
                                onChange={onSearch}
                                placeholder="Cari kode, nama, NIK…"
                                label="Cari berkas"
                            />
                        }
                    >
                        <Combobox
                            className="w-full sm:w-40"
                            searchable={false}
                            options={[
                                { value: 'mine', label: 'Berkas saya' },
                                { value: 'all', label: 'Semua Kasi Analis' },
                            ]}
                            value={filters.scope}
                            onChange={(v) =>
                                visit({
                                    scope: (v ?? 'mine') as 'mine' | 'all',
                                })
                            }
                        />
                        <Combobox
                            className="w-full sm:w-44"
                            searchable={false}
                            options={statuses}
                            value={filters.status}
                            onChange={(v) => visit({ status: v })}
                        />
                        {hasFilters && (
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => clear({ status: null })}
                            >
                                <X /> Atur ulang
                            </Button>
                        )}
                    </FilterBar>
                }
                columns={columns}
                sort={{
                    sort: filters.sort,
                    direction: filters.direction,
                    onSort: sortBy,
                }}
                empty={{
                    icon: <CalendarDays />,
                    title: hasFilters
                        ? 'Tidak ada berkas yang cocok dengan filter'
                        : filters.scope === 'mine'
                          ? 'Tidak ada berkas yang menunggu jadwal dari Anda'
                          : 'Tidak ada berkas yang menunggu jadwal',
                    description: hasFilters
                        ? 'Coba pencarian lain atau atur ulang filter.'
                        : 'Berkas yang diajukan, dan berkas yang dikembalikan surveyor, tampil di sini. Pilih "Semua status" untuk melihat berkas terjadwal juga.',
                }}
                pagination={{
                    meta: loans,
                    perPage: filters.per_page,
                    options: perPageOptions,
                    onPage: (page) => visit({ page }),
                    onPerPage: (per_page) => visit({ per_page }),
                }}
            />

            <ScheduleDialog
                key={scheduling?.id ?? 'none'}
                row={scheduling}
                onClose={() => setScheduling(null)}
            />
            <ReasonDialog
                title="Batalkan jadwal survei"
                description="Berkas kembali ke Kasi Analis untuk dijadwalkan ulang."
                action={cancelUrl}
                confirmLabel="Batalkan jadwal"
                onClose={() => setCancelUrl(null)}
            />
            <ReasonDialog
                title="Batalkan pengajuan"
                description="Pengajuan ditutup dan tidak bisa dibuka kembali."
                action={voidUrl}
                confirmLabel="Batalkan pengajuan"
                onClose={() => setVoidUrl(null)}
            />

            <Modal
                open={history !== null}
                onOpenChange={(open) => !open && setHistory(null)}
                title="Riwayat penjadwalan"
                description={
                    history
                        ? `${history.application_code} · ${history.full_name}`
                        : undefined
                }
            >
                <ul className="max-h-[60vh] divide-y divide-line overflow-auto">
                    {history?.history.length === 0 && (
                        <li className="p-4 text-center text-xs text-muted">
                            Belum ada catatan.
                        </li>
                    )}
                    {history?.history.map((h) => (
                        <li key={h.id} className="px-4 py-2 text-sm">
                            <p className="font-medium">
                                {h.action}
                                {h.survey_date &&
                                    ` · ${formatDate(h.survey_date)}`}
                            </p>
                            <p className="text-xs text-muted">
                                {[h.surveyor_name, h.note ?? h.reason]
                                    .filter(Boolean)
                                    .join(' · ') || '–'}
                            </p>
                            <p className="text-[11px] text-muted">
                                {h.created_by} · {h.created_at}
                            </p>
                        </li>
                    ))}
                </ul>
            </Modal>
        </>
    );
}
