// resources/js/pages/permissions/index.tsx
import { Head, router, useForm } from '@inertiajs/react';
import { KeyRound, Trash2, Wand2, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Combobox } from '@/components/ui/combobox';
import { ConfirmDialog, DialogFooter, Modal } from '@/components/ui/dialog';
import { Field } from '@/components/ui/field';
import { FilterBar, SearchInput } from '@/components/ui/filter-bar';
import { Input } from '@/components/ui/input';
import { DataTable } from '@/components/ui/data-table';
import type { Column } from '@/components/ui/data-table';
import { Badge, PageHeader } from '@/components/ui/misc';
import type { PageMeta } from '@/components/ui/pagination';
import { Tip } from '@/components/ui/tooltip';
import { useListQuery } from '@/hooks/use-list-query';

type Row = {
    id: number;
    name: string;
    entity: string;
    action: string;
    module: string | null;
    custom: boolean;
    roles: number;
};
type Filters = {
    search: string;
    entity: string | null;
    type: 'system' | 'custom' | null;
    per_page: number;
};
type Props = {
    permissions: { data: Row[] } & PageMeta;
    filters: Filters;
    entities: string[];
    actions: string[];
};

const TYPES = [
    { value: 'system', label: 'Sistem' },
    { value: 'custom', label: 'Kustom' },
];
const DEFAULTS = { per_page: 25 };

export default function PermissionsIndex({
    permissions,
    filters,
    entities,
    actions,
}: Props) {
    const [generating, setGenerating] = useState(false);
    const [toDelete, setToDelete] = useState<Row | null>(null);
    const [deleting, setDeleting] = useState(false);
    const form = useForm({ entity: '', actions: actions as string[] });
    const { visit, search, onSearch, clear, loading, error } =
        useListQuery<Filters>({
            url: '/permissions',
            filters,
            defaults: DEFAULTS,
            only: ['permissions', 'filters'],
        });

    const hasFilters = Boolean(
        filters.search || filters.entity || filters.type,
    );

    const openGenerator = () => {
        form.clearErrors();
        form.setData({ entity: '', actions });
        setGenerating(true);
    };

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        form.post('/permissions/generate', {
            preserveScroll: true,
            onSuccess: () => setGenerating(false),
        });
    };

    const confirmDelete = () => {
        if (!toDelete) {
            return;
        }
        router.delete(`/permissions/${toDelete.id}`, {
            preserveScroll: true,
            onStart: () => setDeleting(true),
            onFinish: () => {
                setDeleting(false);
                setToDelete(null);
            },
        });
    };

    const toggle = (action: string, on: boolean) =>
        form.setData(
            'actions',
            on
                ? actions.filter(
                      (a) => a === action || form.data.actions.includes(a),
                  )
                : form.data.actions.filter((a) => a !== action),
        );

    const columns: Column<Row>[] = [
        {
            key: 'name',
            header: 'Izin',
            className: 'font-mono text-xs',
            cell: (p) => p.name,
        },
        {
            key: 'module',
            header: 'Modul',
            hideBelow: 'sm',
            cell: (p) => p.module ?? <span className="text-muted">–</span>,
        },
        {
            key: 'type',
            header: 'Jenis',
            cell: (p) => (
                <Badge tone={p.custom ? 'info' : 'neutral'}>
                    {p.custom ? 'Kustom' : 'Sistem'}
                </Badge>
            ),
        },
        {
            key: 'roles',
            header: 'Peran',
            align: 'right',
            className: 'tabular-nums',
            cell: (p) => p.roles,
        },
        {
            key: 'actions',
            header: 'Aksi',
            srOnly: true,
            narrow: true,
            align: 'right',
            cell: (p) =>
                p.custom && (
                    <Tip label="Hapus">
                        <Button
                            variant="ghost"
                            size="icon"
                            aria-label={`Hapus ${p.name}`}
                            onClick={() => setToDelete(p)}
                        >
                            <Trash2 />
                        </Button>
                    </Tip>
                ),
        },
    ];

    return (
        <>
            <Head title="Data Perizinan" />
            <PageHeader
                title="Data Perizinan"
                description="Semua item izin. Izin sistem ditetapkan di kode; izin kustom dibuat lewat generator."
                actions={
                    <Button onClick={openGenerator}>
                        <Wand2 /> Buat izin
                    </Button>
                }
            />

            <DataTable
                rows={permissions.data}
                rowKey={(r) => r.id}
                loading={loading}
                error={error}
                onRetry={() => visit({})}
                toolbar={
                    <FilterBar
                        search={
                            <SearchInput
                                value={search}
                                onChange={onSearch}
                                placeholder="Cari izin…"
                                label="Cari izin"
                            />
                        }
                    >
                        <Combobox
                            className="w-full sm:w-48"
                            clearable
                            placeholder="Entitas"
                            options={entities.map((e) => ({
                                value: e,
                                label: e,
                            }))}
                            value={filters.entity}
                            onChange={(v) => visit({ entity: v })}
                        />
                        <Combobox
                            className="w-full sm:w-36"
                            clearable
                            searchable={false}
                            placeholder="Jenis"
                            options={TYPES}
                            value={filters.type}
                            onChange={(v) =>
                                visit({ type: v as Filters['type'] })
                            }
                        />
                        {hasFilters && (
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() =>
                                    clear({ entity: null, type: null })
                                }
                            >
                                <X /> Atur ulang
                            </Button>
                        )}
                    </FilterBar>
                }
                columns={columns}
                empty={{
                    icon: <KeyRound />,
                    title: hasFilters
                        ? 'Tidak ada izin yang cocok dengan filter'
                        : 'Belum ada izin',
                }}
                pagination={{
                    meta: permissions,
                    perPage: filters.per_page,
                    options: [10, 25, 50],
                    onPage: (page) => visit({ page }),
                    onPerPage: (per_page) => visit({ per_page }),
                }}
            />

            <Modal
                open={generating}
                onOpenChange={setGenerating}
                title="Generator izin standar"
                description="Membuat izin entitas.aksi; yang sudah ada dilewati."
            >
                <form onSubmit={submit} noValidate>
                    <div className="flex flex-col gap-3 p-4">
                        <Field
                            label="Entitas"
                            required
                            error={form.errors.entity}
                            hint='Huruf kecil dengan tanda hubung, mis. "credit-analysis".'
                        >
                            <Input
                                autoFocus
                                value={form.data.entity}
                                onChange={(e) =>
                                    form.setData('entity', e.target.value)
                                }
                                aria-invalid={!!form.errors.entity}
                            />
                        </Field>
                        <Field
                            label="Aksi standar"
                            error={
                                form.errors.actions ??
                                (form.errors as Record<string, string>)[
                                    'actions.0'
                                ]
                            }
                        >
                            <div className="grid grid-cols-2 gap-x-4 gap-y-1.5 rounded-md border border-line p-2">
                                {actions.map((a) => (
                                    <label
                                        key={a}
                                        className="flex items-center gap-1.5 font-mono text-xs"
                                    >
                                        <input
                                            type="checkbox"
                                            className="accent-primary"
                                            checked={form.data.actions.includes(
                                                a,
                                            )}
                                            onChange={(e) =>
                                                toggle(a, e.target.checked)
                                            }
                                        />
                                        {a}
                                    </label>
                                ))}
                            </div>
                        </Field>
                        <p className="text-xs text-muted">
                            Sebuah izin baru melindungi sesuatu setelah route
                            atau policy memeriksanya. Super Admin otomatis
                            menerima izin baru.
                        </p>
                    </div>
                    <DialogFooter>
                        <Button
                            variant="outline"
                            onClick={() => setGenerating(false)}
                        >
                            Batal
                        </Button>
                        <Button type="submit" loading={form.processing}>
                            Buat izin
                        </Button>
                    </DialogFooter>
                </form>
            </Modal>

            <ConfirmDialog
                open={toDelete !== null}
                onOpenChange={(open) => !open && !deleting && setToDelete(null)}
                title="Hapus izin?"
                description={
                    <>
                        Ini menghapus <strong>{toDelete?.name}</strong>. Izin
                        ini tidak dipegang peran mana pun.
                    </>
                }
                loading={deleting}
                onConfirm={confirmDelete}
            />
        </>
    );
}

// adminkit/resources/js/pages/Permissions.vue
<script setup>
import { computed, ref } from 'vue';
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { Download, KeyRound, Lock, Pencil, Plus, Save, Trash2, Wand2, X } from 'lucide-vue-next';

import FormActions from '@/components/composite/FormActions.vue';
import AppLayout from '@/components/layout/AppLayout.vue';
import { menuLabelOf } from '@/composables/useMenuLabel';
import Badge from '@/components/ui/Badge.vue';
import Button from '@/components/ui/Button.vue';
import Checkbox from '@/components/ui/Checkbox.vue';
import Combobox from '@/components/ui/Combobox.vue';
import Dialog from '@/components/ui/Dialog.vue';
import DropdownMenuItem from '@/components/ui/DropdownMenuItem.vue';
import DropdownMenuSeparator from '@/components/ui/DropdownMenuSeparator.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';
import ConfirmDeleteDialog from '@/components/composite/ConfirmDeleteDialog.vue';
import DataTableCard from '@/components/composite/DataTableCard.vue';
import RowActions from '@/components/composite/RowActions.vue';
import { ACTION } from '@/constants/labels';
import { useServerTable } from '@/composables/useServerTable';
import { all, max, min, required } from '@/lib/validators';
import { useLiveValidation } from '@/composables/useLiveValidation';

const props = defineProps({
    permissions: { type: Object, required: true },
    filters: { type: Object, default: () => ({}) },
    entityOptions: { type: Array, default: () => [] },
    abilityOptions: { type: Array, default: () => [] },
});

const page = usePage();
const canManage = computed(() => (page.props.auth?.user?.permissions ?? []).includes('permissions.manage'));

const columns = [
    { key: 'name', label: 'Nama Izin' },
    { key: 'entity', label: 'Entitas', hideBelow: 'sm' },
    { key: 'ability', label: 'Aksi', hideBelow: 'md' },
    { key: 'guard_name', label: 'Guard', hideBelow: 'lg' },
    { key: 'roles_count', label: 'Peranan', align: 'right' },
    { key: 'actions', label: '', align: 'right', width: '48px', sortable: false },
];

const { query, loading, onSearch, onSort, onPage, onPerPage, onFilter, sortState } = useServerTable({
    url: '/permissions',
    only: ['permissions', 'filters', 'entityOptions'],
    initial: {
        search: props.filters.search ?? '',
        sort: props.filters.sort ?? 'name',
        dir: props.filters.dir ?? 'asc',
        entity: props.filters.entity || 'all',
        page: props.permissions.meta.page ?? 1,
        per_page: props.permissions.meta.per_page ?? 10,
    },
});

/* ── Dialog Tambah / Ubah ────────────────────────────────────────────── */
const dialogOpen = ref(false);
const editing = ref(null);
const form = useForm({ name: '' });

const check = useLiveValidation(form, {
    name: all(
        required('nama izin'),
        min(5, 'Nama Izin'),
        max(80, 'Nama Izin'),
        (value) =>
            value && !/^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$/.test(value)
                ? 'Nama izin harus berformat entitas.aksi memakai huruf kecil, mis. users.view.'
                : '',
    ),
});

const openCreate = () => {
    editing.value = null;
    form.defaults({ name: '' });
    form.reset();
    form.clearErrors();
    dialogOpen.value = true;
};

const openEdit = (row) => {
    editing.value = row;
    form.defaults({ name: row.name });
    form.reset();
    form.clearErrors();
    dialogOpen.value = true;
};

const submit = () =>
    check.submit(() => {
        const options = { preserveScroll: true, onSuccess: () => (dialogOpen.value = false) };
        if (editing.value) form.put(`/permissions/${editing.value.id}`, options);
        else form.post('/permissions', options);
    });

/* ── Generator izin standar ──────────────────────────────────────────── */
const generatorOpen = ref(false);
const generator = useForm({ entity: '', abilities: [...props.abilityOptions] });

const openGenerator = () => {
    generator.clearErrors();
    generator.reset();
    generatorOpen.value = true;
};

const toggleAbility = (ability, checked) => {
    generator.abilities = checked
        ? [...generator.abilities, ability]
        : generator.abilities.filter((a) => a !== ability);
};

const submitGenerator = () =>
    generator.post('/permissions/generate', {
        preserveScroll: true,
        onSuccess: () => (generatorOpen.value = false),
    });

/* ── Ekspor Excel mengikuti filter aktif ───────────────────────────────── */
const exportUrl = computed(() => {
    const params = new URLSearchParams();
    if (query.search) params.set('search', query.search);
    if (query.entity && query.entity !== 'all') params.set('entity', query.entity);
    params.set('sort', query.sort);
    params.set('dir', query.dir);

    return `/permissions/export?${params.toString()}`;
});

/* ── Hapus & aksi massal ─────────────────────────────────────────────── */
const deleting = ref(null);
const deleteForm = useForm({});
const confirmDelete = () =>
    deleteForm.delete(`/permissions/${deleting.value.id}`, {
        preserveScroll: true,
        onFinish: () => (deleting.value = null),
    });

const selected = ref([]);
const bulkForm = useForm({ ids: [] });
const bulkConfirm = ref(false);

const runBulkDelete = () => {
    bulkForm.ids = [...selected.value];
    bulkForm.post('/permissions/bulk-destroy', {
        preserveScroll: true,
        onSuccess: () => {
            selected.value = [];
            bulkConfirm.value = false;
        },
    });
};

const pageTitle = computed(() => menuLabelOf('/permissions', 'Perizinan'));
</script>

<template>
    <Head :title="pageTitle" />
    <AppLayout>
        <div class="space-y-6" data-testid="permissions-page-view">
            <DataTableCard
                server
                :title="pageTitle"
                testid="permissions"
                :columns="columns"
                :rows="props.permissions.data"
                :meta="props.permissions.meta"
                :search="query.search"
                :sort="sortState"
                :loading="loading"
                :empty-icon="KeyRound"
                empty-title="Belum ada izin"
                empty-description="Tambahkan izin dengan format entitas.aksi, mis. projects.view."
                :show-refresh="false"
                :selectable="canManage"
                :selected="selected"
                @update:selected="selected = $event"
                @update:search="onSearch"
                @update:sort="onSort"
                @update:page="onPage"
                @update:per-page="onPerPage"
            >
                <template #filters>
                    <Combobox
                        :model-value="query.entity"
                        :options="props.entityOptions"
                        placeholder="Semua Entitas"
                        class="w-[160px]"
                        data-testid="permissions-filter-entity"
                        @update:model-value="onFilter('entity', $event)"
                    />
                </template>

                <template #bulk-actions>
                    <Button
                        variant="destructive"
                        size="sm"
                        :disabled="bulkForm.processing"
                        data-testid="permissions-bulk-delete"
                        @click="bulkConfirm = true"
                    >
                        <Trash2 class="size-4" /> {{ ACTION.delete }}
                    </Button>
                </template>

                <template #header-action>
                    <Button variant="outline" size="sm" as="a" :href="exportUrl" data-testid="permissions-export">
                        <Download class="size-4" /> {{ ACTION.export }}
                    </Button>
                    <Button
                        v-if="canManage"
                        variant="outline"
                        size="sm"
                        data-testid="permissions-generate"
                        @click="openGenerator"
                    >
                        <Wand2 class="size-4" /> Generator
                    </Button>
                    <Button v-if="canManage" size="sm" data-testid="permissions-add" @click="openCreate">
                        <Plus class="size-4" /> {{ ACTION.add }}
                    </Button>
                </template>

                <template #cell-name="{ row }">
                    <span class="flex items-center gap-2 font-mono text-xs font-medium">
                        {{ row.name }}
                        <Lock v-if="row.locked" class="size-3.5 text-muted-foreground" aria-label="Izin inti" />
                    </span>
                </template>

                <template #cell-ability="{ row }">
                    <Badge variant="secondary" class="font-normal">{{ row.ability }}</Badge>
                </template>

                <template #cell-guard_name="{ row }">
                    <span class="font-mono text-xs text-muted-foreground">{{ row.guard_name }}</span>
                </template>

                <template #cell-roles_count="{ row }">
                    <span class="tabular-nums">{{ row.roles_count }}</span>
                </template>

                <template #cell-actions="{ row }">
                    <RowActions v-if="canManage && !row.locked" :testid="`permissions-actions-${row.id}`">
                        <DropdownMenuItem :data-testid="`permissions-edit-${row.id}`" @click="openEdit(row)">
                            <Pencil />{{ ACTION.edit }}
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                            class="text-destructive data-[highlighted]:text-destructive"
                            :data-testid="`permissions-delete-${row.id}`"
                            @click="deleting = row"
                        >
                            <Trash2 />{{ ACTION.delete }}
                        </DropdownMenuItem>
                    </RowActions>
                </template>
            </DataTableCard>

            <!-- Dialog Tambah / Ubah Izin -->
            <Dialog v-model:open="dialogOpen" :title="editing ? 'Ubah Izin' : 'Tambah Izin'" class="max-w-md">
                <form
                    id="permission-form"
                    class="form-dense space-y-[var(--field-gap)]"
                    novalidate
                    @submit.prevent="submit"
                >
                    <div class="space-y-[var(--item-gap)]">
                        <Label for="p-name">Nama Izin</Label>
                        <Input
                            id="p-name"
                            v-model="form.name"
                            class="font-mono"
                            maxlength="80"
                            data-testid="permission-form-name"
                            @blur="check.validate('name')"
                        />
                        <p
                            v-if="form.errors.name"
                            class="text-xs font-medium text-destructive"
                            data-testid="permission-form-name-error"
                        >
                            {{ form.errors.name }}
                        </p>
                        <p v-else class="text-xs text-muted-foreground">
                            Format <span class="font-mono">entitas.aksi</span>, mis.
                            <span class="font-mono">projects.view</span> atau
                            <span class="font-mono">projects.delete_any</span>.
                        </p>
                    </div>
                </form>

                <template #footer>
                    <FormActions
                        cancel-testid="permission-form-cancel"
                        submit-testid="permission-form-save"
                        submit-type="submit"
                        form="permission-form"
                        :processing="form.processing"
                        @cancel="dialogOpen = false"
                    />
                </template>
            </Dialog>

            <!-- Dialog Generator Izin Standar -->
            <Dialog v-model:open="generatorOpen" title="Generator Izin Standar" class="max-w-md">
                <div class="form-dense space-y-[var(--field-gap)]">
                    <div class="space-y-[var(--item-gap)]">
                        <Label for="g-entity">Entitas</Label>
                        <Input
                            id="g-entity"
                            v-model="generator.entity"
                            class="font-mono"
                            
                            maxlength="40"
                            data-testid="generator-entity"
                        />
                        <p v-if="generator.errors.entity" class="text-xs font-medium text-destructive" data-testid="generator-entity-error">
                            {{ generator.errors.entity }}
                        </p>
                    </div>
                    <div class="space-y-[var(--item-gap)]">
                        <Label>Aksi Standar</Label>
                        <ul class="grid grid-cols-2 gap-1.5 rounded-lg border p-2">
                            <li
                                v-for="ability in props.abilityOptions"
                                :key="ability"
                                class="flex items-center gap-2"
                            >
                                <Checkbox
                                    :model-value="generator.abilities.includes(ability)"
                                    :aria-label="ability"
                                    :data-testid="`generator-ability-${ability}`"
                                    @update:model-value="toggleAbility(ability, $event)"
                                />
                                <span class="font-mono text-xs">{{ ability }}</span>
                            </li>
                        </ul>
                        <p v-if="generator.errors.abilities" class="text-xs font-medium text-destructive" data-testid="generator-abilities-error">
                            {{ generator.errors.abilities }}
                        </p>
                        <p v-else class="text-xs text-muted-foreground">
                            Izin dibuat dengan pola <span class="font-mono">entitas.aksi</span>; yang sudah ada dilewati.
                        </p>
                    </div>
                </div>

                <template #footer>
                    <FormActions
                        cancel-testid="generator-cancel"
                        submit-testid="generator-submit"
                        submit-label="Buat Izin"
                        :submit-icon="Wand2"
                        :processing="generator.processing"
                        @cancel="generatorOpen = false"
                        @submit="submitGenerator"
                    />
                </template>
            </Dialog>

            <ConfirmDeleteDialog
                :open="bulkConfirm"
                title="Hapus Izin Terpilih?"
                :description="`${selected.length} izin akan dihapus. Izin inti bawaan modul dilewati.`"
                :processing="bulkForm.processing"
                @update:open="bulkConfirm = false"
                @confirm="runBulkDelete"
            />

            <ConfirmDeleteDialog
                :open="Boolean(deleting)"
                title="Hapus Izin?"
                :processing="deleteForm.processing"
                @update:open="deleting = null"
                @confirm="confirmDelete"
            />
        </div>
    </AppLayout>
</template>
